name: Python package

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions coverage
    - name: Test with tox
      run: tox
    - name: Generate coverage badge
      run: |
        total=`coverage report | grep -Eo '[0-9]+\.[0-9]+' | tail -n 1`

        if (( $(echo "$total <= 50" | bc -l) )) ; then
            COLOR=red
        elif (( $(echo "$total > 80" | bc -l) )); then
            COLOR=green
        else
            COLOR=orange
        fi
        echo $COLOR
        curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > coverage-badge.svg
    - name: Push badge to amdd-repos
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUBKEY }}
      with:
        source_file: 'coverage-badge.svg'
        destination_repo: 'jens-hummelshoej-tri/amdd-repos'
        destination_folder: 'paretl'
        user_email: 'jens.hummelshoej@tri.global'
        user_name: 'jens-hummelshoej-tri'
        commit_message: 'From github action'
